# Site's name:
name: 'Calagator'

# Site's tagline:
tagline: "Portland's Tech Calendar"

# Site's URL with trailing slash:
url: 'http://calagator.org/'

# Default timezone for Rails, run "rake time:zones:all" for options:
timezone: 'Pacific Time (US & Canada)'

# Default timezone for OS:
# FIXME this is an evil temporary workaround, in future the "timezone" setting above will be enough
tz: 'PST8PDT'

# Google map to display on /venues page:
venues_google_map_options:
  # Zoom magnification level:
  zoom: 12
  # Center of the map, in latitude and longitude:
  center: [45.518493, -122.660737]
